In [ ]:
#!pip install scikit-learn

  Using cached scikit_learn-1.7.0-cp312-cp312-win_amd64.whl.metadata (14 kB)
  Using cached numpy-2.3.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
  Using cached scipy-1.15.3-cp312-cp312-win_amd64.whl.metadata (60 kB)
  Using cached joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.7.0-cp312-cp312-win_amd64.whl (10.7 MB)
Using cached joblib-1.5.1-py3-none-any.whl (307 kB)
Using cached numpy-2.3.0-cp312-cp312-win_amd64.whl (12.7 MB)
Using cached scipy-1.15.3-cp312-cp312-win_amd64.whl (41.0 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)

   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- 

In [ ]:
#!pip install pandas

  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   --------------------------------- ------ 9.2/11.0 MB 40.7 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 36.1 MB/s eta 0:00:00
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------

In [3]:
import pandas as pd

In [4]:
data = pd.read_json("http://localhost:3000/restaurant/train")
data.head() # 앞쪽 데이터프레임의 5줄, tail() : 끝쪽 5개

seq  zipcode                              address zonecode  \
0    1  450-831                 경기도 평택시 합정동 731-32번지            
1    2  712-907     경상북도 경산시 하양읍 서사리 342 드림스퀘어1 101호    38699   
2    3  135-998          서울특별시 강남구 대치동 935-10번지 지상1층    06207   
3    4  400-012             인천광역시 중구 중앙동2가 24-2번지 1층    22314   
4    5  301-824  대전광역시 중구 선화동 151-13 선화현대빌딩 지하1층 11호    34844   

                               roadAddress category          name        lat  \
0                                                한식  2000년 뼈다귀해장국  36.992415   
1      경상북도 경산시 하양읍 서사도리9로 25, 드림스퀘어1 101호      경양식   1인칭피자시점 하양점  35.916785   
2           서울특별시 강남구 선릉로64길 30 (대치동,지상1층)       한식        트레플 유오  37.498290   
3       인천광역시 중구 제물량로232번안길 27 (중앙동2가, 1층)       까페          구두식탁  37.472887   
4  대전광역시 중구 보문로 337, 선화현대빌딩 지하1층 11호 (선화동)       분식         정담손만두  36.332514   

          lon  
0  127.087877  
1  128.810302  
2  127.051869  
3  126.618125  
4  127.415302

In [6]:
train_input = data[['lat', 'lon']].to_numpy()
train_input[:10]

array([[ 36.99241476, 127.08787695],
       [ 35.91678511, 128.81030222],
       [ 37.4982898 , 127.05186851],
       [ 37.47288749, 126.61812499],
       [ 36.33251402, 127.41530162],
       [ 37.45915265, 126.71199808],
       [ 37.44873804, 126.72809469],
       [ 37.46265312, 126.70958687],
       [ 37.51644066, 126.71937685],
       [ 37.47539792, 126.69495765]])

In [7]:
train_target = data['seq'].to_numpy()
train_target[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [9]:
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)

In [10]:
kn = KNeighborsClassifier(n_neighbors=50, p=1)
kn.fit(train_scaled, train_target);

c:\restaurant\.venv\Lib\site-packages\sklearn\utils\multiclass.py:213: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  y_type = type_of_target(y, input_name="y")


In [12]:
import numpy as np
current = ss.transform(np.array([[35.097993954721815, 129.03321328510245]]))
current

array([[-1.6560828 ,  2.10262544]])

In [13]:
_, indexes = kn.kneighbors(current)
indexes

array([[88818, 18894, 96549,  2716,  9754, 36616, 89810, 90354,  5128,
        27608, 30194, 15894, 83379, 91416, 30193, 91417, 94538, 34600,
        98334, 98336, 98335,  6481, 83380, 31594, 18759, 27609, 96584,
        90899, 94582, 22209,  1902,  2046, 28003, 93402, 37244,   509,
        95468, 82973, 21312, 21347, 21348, 17951, 97495, 87164, 94326,
        10443, 97674,   713,  5373,  9694]])

In [14]:
train_target[indexes]

array([[88819, 18895, 96550,  2717,  9755, 36617, 89811, 90355,  5129,
        27609, 30195, 15895, 83380, 91417, 30194, 91418, 94539, 34601,
        98335, 98337, 98336,  6482, 83381, 31595, 18760, 27610, 96585,
        90900, 94583, 22210,  1903,  2047, 28004, 93403, 37245,   510,
        95469, 82974, 21313, 21348, 21349, 17952, 97496, 87165, 94327,
        10444, 97675,   714,  5374,  9695]])